# This workflow generates the list of banned cards upon pushes
name: update_banlist

on:
    push:
        branches: "**"
    workflow_dispatch: {} # Allows manual triggering from Actions tab

jobs:
    update_banlist:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.11
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -e .
            - name: Generate JSON banlist
              uses: jannekem/run-python-script-action@v1
              with:
                script: |
                  from mtgbp_banlists import HTMLBanlist, JSONBanlist
                  JSONBanlist.export()
                  HTMLBanlist.export()
            - name: Add & commit JSON banlist
              uses: EndBug/add-and-commit@v9
              with:
                add: "docs/current_banlist.json docs/announcement_history.html"
                author_name: FunkyMax
                author_email: polak.maxence@orange.fr
                commit: --signoff
                committer_name: Spigushe
                committer_email: martin.cuchet@gmail.com
                default_author: github_actor
                fetch: false
                message: "[AUTO] Banlist update"
                new_branch: ""
                pathspec_error_handling: exitImmediately
